//

export const fairFixture = {
  id: "art-palm-springs-2019",
  __id: "RmFpcjphcnQtcGFsbS1zcHJpbmdzLTIwMTk=",
  _id: "5c17b160ffbbc72eef33040c",
  name: "Art Palm Springs 2019",
  counts: { artists: 279, partners: 33 },
  partner_names: {
    edges: [
      {
        node: {
          id: "blue-rain-gallery-blue-rain-gallery-at-art-palm-springs-2019",
          partner: {
            __typename: "Partner",
            profile: {
              name: "Blue Rain Gallery",
              id: "blue-rain-gallery",
              _id: "58b4acca139b2178c2554ab7",
              __id: "UHJvZmlsZTpibHVlLXJhaW4tZ2FsbGVyeQ==",
            },
            __id: "UGFydG5lcjpibHVlLXJhaW4tZ2FsbGVyeQ==",
          },
          __id: "U2hvdzpibHVlLXJhaW4tZ2FsbGVyeS1ibHVlLXJhaW4tZ2FsbGVyeS1hdC1hcnQtcGFsbS1zcHJpbmdzLTIwMTk=",
        },
      },
      {
        node: {
          id: "fabrik-projects-gallery-fabrik-projects-gallery-at-art-palm-springs-2019",
          partner: {
            __typename: "Partner",
            profile: {
              name: "Fabrik Projects Gallery",
              id: "fabrik-gallery",
              _id: "5941712db202a34d5c754b36",
              __id: "UHJvZmlsZTpmYWJyaWstZ2FsbGVyeQ==",
            },
            __id: "UGFydG5lcjpmYWJyaWstcHJvamVjdHMtZ2FsbGVyeQ==",
          },
          __id:
            "U2hvdzpmYWJyaWstcHJvamVjdHMtZ2FsbGVyeS1mYWJyaWstcHJvamVjdHMtZ2FsbGVyeS1hdC1hcnQtcGFsbS1zcHJpbmdzLTIwMTk=",
        },
      },
    ],
  },
  artists_names: {
    edges: [
      {
        node: {
          name: "00100011",
          href: "/artist/00100011-1",
          id: "00100011-1",
          _id: "5c52df9966715663f8ba7690",
          __id: "QXJ0aXN0OjAwMTAwMDExLTE=",
        },
      },
      {
        node: {
          name: "David Adey",
          href: "/artist/david-adey",
          id: "david-adey",
          _id: "573624967622dd1d1c000194",
          __id: "QXJ0aXN0OmRhdmlkLWFkZXk=",
        },
      },
    ],
  },
  image: {
    image_url: "https://d32dm0rphc51dk.cloudfront.net/WHcii__DzI14sEuw5m3qaA/:version.jpg",
    aspect_ratio: 1,
    url: "https://d32dm0rphc51dk.cloudfront.net/WHcii__DzI14sEuw5m3qaA/wide.jpg",
  },
  profile: {
    icon: {
      id: "5c58b4d60961cb5391fbe8d5",
      href: null,
      height: 280,
      width: 280,
      url: "https://d32dm0rphc51dk.cloudfront.net/D-QEVpAZcck8VXEgwNrhog/untouched-png.png",
    },
    __id: "UHJvZmlsZTphcnQtcGFsbS1zcHJpbmdzLTIwMTk=",
    id: "art-palm-springs-2019",
    name: "Art Palm Springs 2019",
    is_followed: false,
  },
  start_at: "2019-02-15T11:00:00+00:00",
  end_at: "2019-02-18T17:00:00+00:00",
  hours:
    "**Opening Night Preview:** Thursday, February 14 from 5-9pm | VIP Ticket Holders Only\r\n\r\n**General Admission:**\r\nFriday, February 15 | 11am-7pm \r\nSaturday, February 16 | 11am-6pm \r\nSunday, February 17 | 11am-6pm \r\nMonday, February 18 | 12pm-5pm ",
  location: {
    __id: "TG9jYXRpb246NWMxN2IxOWQ4ODQxYzQ2ZTM5NGM4MmI2",
    id: "5c17b19d8841c46e394c82b6",
    city: "Palm Springs",
    address: "",
    address_2: "",
    postal_code: "92262",
    summary: "Palm Springs Convention Center\r\n277 N Avenida Caballeros\r\nPalm Springs, CA 92262",
    coordinates: { lat: 33.828735, lng: -116.537426 },
    day_schedules: null,
  },
  organizer: { website: null },
  about:
    "Art Palm Springs is the premier art fair in the Southwest presenting post-war and contemporary art. This years edition will brings galleries from Asia, Europe, North and South America representing hundreds of artists to the Palm Springs Convention Center. The Fair is strategically scheduled over the extended President’s Day Weekend coinciding with Palm Springs Modernism Week at the height of the Coachella Valley’s season. Art Palm Springs and Modernism Week turn the Desert into a cultural mecca over this weekend, attracting close to 15,000 acquisition oriented art lovers to the Fair year after year.",
  ticketsLink: "https://www.showclix.com/events/23121",
  shows: {
    pageInfo: { hasNextPage: true, startCursor: "YXJyYXljb25uZWN0aW9uOjA=", endCursor: "YXJyYXljb25uZWN0aW9uOjQ=" },
    edges: [
      {
        cursor: "YXJyYXljb25uZWN0aW9uOjA=",
        node: {
          id: "blue-rain-gallery-blue-rain-gallery-at-art-palm-springs-2019",
          _id: "5c2e505c0cf1100007b43866",
          artworks_connection: {
            edges: [
              {
                node: {
                  id: "brad-overton-la-reina",
                  __id: "QXJ0d29yazpicmFkLW92ZXJ0b24tbGEtcmVpbmE=",
                  image: {
                    aspect_ratio: 1,
                    url: "https://d32dm0rphc51dk.cloudfront.net/OwQwHKPmc4_Vtm_9lkac1w/large.jpg",
                  },
                  title: "La Reina",
                  date: "2018",
                  sale_message: "$20,000",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Brad Overton", __id: "QXJ0aXN0OmJyYWQtb3ZlcnRvbg==" }],
                  partner: { name: "Blue Rain Gallery", __id: "UGFydG5lcjpibHVlLXJhaW4tZ2FsbGVyeQ==" },
                  href: "/artwork/brad-overton-la-reina",
                },
              },
              {
                node: {
                  id: "brad-overton-coyo",
                  __id: "QXJ0d29yazpicmFkLW92ZXJ0b24tY295bw==",
                  image: {
                    aspect_ratio: 1.25,
                    url: "https://d32dm0rphc51dk.cloudfront.net/Fe0qeYt_RkNAm4s4f8Qcdw/large.jpg",
                  },
                  title: "Coyo",
                  date: "2018",
                  sale_message: "$22,000",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Brad Overton", __id: "QXJ0aXN0OmJyYWQtb3ZlcnRvbg==" }],
                  partner: { name: "Blue Rain Gallery", __id: "UGFydG5lcjpibHVlLXJhaW4tZ2FsbGVyeQ==" },
                  href: "/artwork/brad-overton-coyo",
                },
              },
              {
                node: {
                  id: "brad-overton-cordelia",
                  __id: "QXJ0d29yazpicmFkLW92ZXJ0b24tY29yZGVsaWE=",
                  image: {
                    aspect_ratio: 1.01,
                    url: "https://d32dm0rphc51dk.cloudfront.net/DHeBmmrch5j-DZd8vaOzNw/large.jpg",
                  },
                  title: "Cordelia",
                  date: "2019",
                  sale_message: "$20,000",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Brad Overton", __id: "QXJ0aXN0OmJyYWQtb3ZlcnRvbg==" }],
                  partner: { name: "Blue Rain Gallery", __id: "UGFydG5lcjpibHVlLXJhaW4tZ2FsbGVyeQ==" },
                  href: "/artwork/brad-overton-cordelia",
                },
              },
              {
                node: {
                  id: "brad-overton-moyetzicate",
                  __id: "QXJ0d29yazpicmFkLW92ZXJ0b24tbW95ZXR6aWNhdGU=",
                  image: {
                    aspect_ratio: 1,
                    url: "https://d32dm0rphc51dk.cloudfront.net/o1CCvc4BgGDkXcH-JKAxgw/large.jpg",
                  },
                  title: "Moyetzicate",
                  date: "2019",
                  sale_message: "$24,000",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Brad Overton", __id: "QXJ0aXN0OmJyYWQtb3ZlcnRvbg==" }],
                  partner: { name: "Blue Rain Gallery", __id: "UGFydG5lcjpibHVlLXJhaW4tZ2FsbGVyeQ==" },
                  href: "/artwork/brad-overton-moyetzicate",
                },
              },
            ],
          },
          name: "Blue Rain Gallery at Art Palm Springs 2019",
          is_fair_booth: true,
          partner: {
            __typename: "Partner",
            name: "Blue Rain Gallery",
            href: "/blue-rain-gallery",
            id: "blue-rain-gallery",
            _id: "58b4acca139b2178c2554ab6",
            __id: "UGFydG5lcjpibHVlLXJhaW4tZ2FsbGVyeQ==",
            profile: {
              _id: "58b4acca139b2178c2554ab7",
              is_followed: false,
              __id: "UHJvZmlsZTpibHVlLXJhaW4tZ2FsbGVyeQ==",
            },
          },
          fair: { name: "Art Palm Springs 2019", __id: "RmFpcjphcnQtcGFsbS1zcHJpbmdzLTIwMTk=" },
          cover_image: { url: "https://d32dm0rphc51dk.cloudfront.net/Z92kkuxZaGBttvjf7V8nzQ/general.jpg" },
          location: { display: "Booth 407", __id: "TG9jYXRpb246NWMyZTUwNWQwY2YxMTAwMDA3YjQzODY3" },
          __id: "U2hvdzpibHVlLXJhaW4tZ2FsbGVyeS1ibHVlLXJhaW4tZ2FsbGVyeS1hdC1hcnQtcGFsbS1zcHJpbmdzLTIwMTk=",
          __typename: "Show",
        },
      },
      {
        cursor: "YXJyYXljb25uZWN0aW9uOjE=",
        node: {
          id: "fabrik-projects-gallery-fabrik-projects-gallery-at-art-palm-springs-2019",
          _id: "5c51fd3c7db50a090a2824a4",
          artworks_connection: {
            edges: [
              {
                node: {
                  id: "betsy-enzensberger-rainbow-popsicle",
                  __id: "QXJ0d29yazpiZXRzeS1lbnplbnNiZXJnZXItcmFpbmJvdy1wb3BzaWNsZQ==",
                  image: {
                    aspect_ratio: 1,
                    url: "https://d32dm0rphc51dk.cloudfront.net/wOTOb94ywotDDppD4oIZvg/large.jpg",
                  },
                  title: "Rainbow Popsicle",
                  date: "2018",
                  sale_message: "$250",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Betsy Enzensberger", __id: "QXJ0aXN0OmJldHN5LWVuemVuc2Jlcmdlcg==" }],
                  partner: { name: "Fabrik Projects Gallery", __id: "UGFydG5lcjpmYWJyaWstcHJvamVjdHMtZ2FsbGVyeQ==" },
                  href: "/artwork/betsy-enzensberger-rainbow-popsicle",
                },
              },
              {
                node: {
                  id: "linda-stelling-be-still-my-beating-heart",
                  __id: "QXJ0d29yazpsaW5kYS1zdGVsbGluZy1iZS1zdGlsbC1teS1iZWF0aW5nLWhlYXJ0",
                  image: {
                    aspect_ratio: 0.6,
                    url: "https://d32dm0rphc51dk.cloudfront.net/KnsgJ1WL6FvJICcRDjIgnA/large.jpg",
                  },
                  title: "Be Still My Beating Heart",
                  date: "",
                  sale_message: "$4,200",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Linda Stelling", __id: "QXJ0aXN0OmxpbmRhLXN0ZWxsaW5n" }],
                  partner: { name: "Fabrik Projects Gallery", __id: "UGFydG5lcjpmYWJyaWstcHJvamVjdHMtZ2FsbGVyeQ==" },
                  href: "/artwork/linda-stelling-be-still-my-beating-heart",
                },
              },
              {
                node: {
                  id: "linda-stelling-fixing-a-hole-where-the-rain-gets-in",
                  __id: "QXJ0d29yazpsaW5kYS1zdGVsbGluZy1maXhpbmctYS1ob2xlLXdoZXJlLXRoZS1yYWluLWdldHMtaW4=",
                  image: {
                    aspect_ratio: 0.75,
                    url: "https://d32dm0rphc51dk.cloudfront.net/KOMM-Vsk3tQXQPcwPctoOQ/large.jpg",
                  },
                  title: "Fixing A Hole Where the Rain Gets In",
                  date: "",
                  sale_message: "$3,900",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Linda Stelling", __id: "QXJ0aXN0OmxpbmRhLXN0ZWxsaW5n" }],
                  partner: { name: "Fabrik Projects Gallery", __id: "UGFydG5lcjpmYWJyaWstcHJvamVjdHMtZ2FsbGVyeQ==" },
                  href: "/artwork/linda-stelling-fixing-a-hole-where-the-rain-gets-in",
                },
              },
              {
                node: {
                  id: "linda-stelling-the-palms",
                  __id: "QXJ0d29yazpsaW5kYS1zdGVsbGluZy10aGUtcGFsbXM=",
                  image: {
                    aspect_ratio: 0.72,
                    url: "https://d32dm0rphc51dk.cloudfront.net/HnkYu6bs2z-UoG7HOYDNIw/large.jpg",
                  },
                  title: "The Palms",
                  date: "",
                  sale_message: "$3,900",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Linda Stelling", __id: "QXJ0aXN0OmxpbmRhLXN0ZWxsaW5n" }],
                  partner: { name: "Fabrik Projects Gallery", __id: "UGFydG5lcjpmYWJyaWstcHJvamVjdHMtZ2FsbGVyeQ==" },
                  href: "/artwork/linda-stelling-the-palms",
                },
              },
            ],
          },
          name: "Fabrik Projects Gallery at Art Palm Springs 2019",
          is_fair_booth: true,
          partner: {
            __typename: "Partner",
            name: "Fabrik Projects Gallery",
            href: "/fabrik-gallery",
            id: "fabrik-projects-gallery",
            _id: "5941712db202a34d5c754b35",
            __id: "UGFydG5lcjpmYWJyaWstcHJvamVjdHMtZ2FsbGVyeQ==",
            profile: {
              _id: "5941712db202a34d5c754b36",
              is_followed: false,
              __id: "UHJvZmlsZTpmYWJyaWstZ2FsbGVyeQ==",
            },
          },
          fair: { name: "Art Palm Springs 2019", __id: "RmFpcjphcnQtcGFsbS1zcHJpbmdzLTIwMTk=" },
          cover_image: { url: "https://d32dm0rphc51dk.cloudfront.net/2kEMmIYFOu4igk9EglI8lw/medium.jpg" },
          location: { display: "", __id: "TG9jYXRpb246NWM1MWZkM2Q3ZGI1MGEwOTBhMjgyNGE1" },
          __id:
            "U2hvdzpmYWJyaWstcHJvamVjdHMtZ2FsbGVyeS1mYWJyaWstcHJvamVjdHMtZ2FsbGVyeS1hdC1hcnQtcGFsbS1zcHJpbmdzLTIwMTk=",
          __typename: "Show",
        },
      },
      {
        cursor: "YXJyYXljb25uZWN0aW9uOjI=",
        node: {
          id: "adamar-fine-arts-adamar-fine-arts-at-art-palm-springs-2019",
          _id: "5c2e505b0cf1100007b43860",
          artworks_connection: {
            edges: [
              {
                node: {
                  id: "tom-wesselmann-wildflowers-bouquet-black-two-handled-vase",
                  __id: "QXJ0d29yazp0b20td2Vzc2VsbWFubi13aWxkZmxvd2Vycy1ib3VxdWV0LWJsYWNrLXR3by1oYW5kbGVkLXZhc2U=",
                  image: {
                    aspect_ratio: 0.75,
                    url: "https://d32dm0rphc51dk.cloudfront.net/-aGYHaUsGfZ4HwmzhEIoRQ/large.jpg",
                  },
                  title: "Wildflowers Bouquet Black (two handled vase)",
                  date: "1988",
                  sale_message: "$200,000 - 300,000",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Tom Wesselmann", __id: "QXJ0aXN0OnRvbS13ZXNzZWxtYW5u" }],
                  partner: { name: "Adamar Fine Arts", __id: "UGFydG5lcjphZGFtYXItZmluZS1hcnRz" },
                  href: "/artwork/tom-wesselmann-wildflowers-bouquet-black-two-handled-vase",
                },
              },
              {
                node: {
                  id: "alex-katz-coca-cola-girls-number-1",
                  __id: "QXJ0d29yazphbGV4LWthdHotY29jYS1jb2xhLWdpcmxzLW51bWJlci0x",
                  image: {
                    aspect_ratio: 1.26,
                    url: "https://d32dm0rphc51dk.cloudfront.net/md0ufnclf7QiFkqwUvQSCA/large.jpg",
                  },
                  title: "Coca Cola Girls #1",
                  date: "2018",
                  sale_message: "$15,000 - 20,000",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Alex Katz", __id: "QXJ0aXN0OmFsZXgta2F0eg==" }],
                  partner: { name: "Adamar Fine Arts", __id: "UGFydG5lcjphZGFtYXItZmluZS1hcnRz" },
                  href: "/artwork/alex-katz-coca-cola-girls-number-1",
                },
              },
              {
                node: {
                  id: "alex-katz-coca-cola-girls-number-6",
                  __id: "QXJ0d29yazphbGV4LWthdHotY29jYS1jb2xhLWdpcmxzLW51bWJlci02",
                  image: {
                    aspect_ratio: 2.01,
                    url: "https://d32dm0rphc51dk.cloudfront.net/7Lr7lriGKB9vFvjK7OxcoA/large.jpg",
                  },
                  title: "Coca Cola Girls #6",
                  date: "2018",
                  sale_message: "$20,000 - 30,000",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Alex Katz", __id: "QXJ0aXN0OmFsZXgta2F0eg==" }],
                  partner: { name: "Adamar Fine Arts", __id: "UGFydG5lcjphZGFtYXItZmluZS1hcnRz" },
                  href: "/artwork/alex-katz-coca-cola-girls-number-6",
                },
              },
              {
                node: {
                  id: "damien-hirst-psalm-expectans-expectavi-7",
                  __id: "QXJ0d29yazpkYW1pZW4taGlyc3QtcHNhbG0tZXhwZWN0YW5zLWV4cGVjdGF2aS03",
                  image: {
                    aspect_ratio: 1,
                    url: "https://d32dm0rphc51dk.cloudfront.net/TPuIgoOfuutcivKlSebJ8Q/large.jpg",
                  },
                  title: "Psalm: Expectans Expectavi",
                  date: "2015",
                  sale_message: "$15,000 - 20,000",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Damien Hirst", __id: "QXJ0aXN0OmRhbWllbi1oaXJzdA==" }],
                  partner: { name: "Adamar Fine Arts", __id: "UGFydG5lcjphZGFtYXItZmluZS1hcnRz" },
                  href: "/artwork/damien-hirst-psalm-expectans-expectavi-7",
                },
              },
            ],
          },
          name: "Adamar Fine Arts at Art Palm Springs 2019",
          is_fair_booth: true,
          partner: {
            __typename: "Partner",
            name: "Adamar Fine Arts",
            href: "/adamar-fine-arts",
            id: "adamar-fine-arts",
            _id: "54b40a37776f720e459d0500",
            __id: "UGFydG5lcjphZGFtYXItZmluZS1hcnRz",
            profile: {
              _id: "54b40a37776f720e459f0500",
              is_followed: false,
              __id: "UHJvZmlsZTphZGFtYXItZmluZS1hcnRz",
            },
          },
          fair: { name: "Art Palm Springs 2019", __id: "RmFpcjphcnQtcGFsbS1zcHJpbmdzLTIwMTk=" },
          cover_image: { url: "https://d32dm0rphc51dk.cloudfront.net/bW9aZEC-saGXeQHeAGt3lg/larger.jpg" },
          location: { display: "Booth 108", __id: "TG9jYXRpb246NWMyZTUwNWMwY2YxMTAwMDA3YjQzODYx" },
          __id: "U2hvdzphZGFtYXItZmluZS1hcnRzLWFkYW1hci1maW5lLWFydHMtYXQtYXJ0LXBhbG0tc3ByaW5ncy0yMDE5",
          __typename: "Show",
        },
      },
      {
        cursor: "YXJyYXljb25uZWN0aW9uOjM=",
        node: {
          id: "vallarino-fine-art-vallarino-fine-art-at-art-palm-springs-2019",
          _id: "5c2e506a0cf1100007b438a1",
          artworks_connection: {
            edges: [
              {
                node: {
                  id: "karel-appel-figure-1",
                  __id: "QXJ0d29yazprYXJlbC1hcHBlbC1maWd1cmUtMQ==",
                  image: {
                    aspect_ratio: 1.26,
                    url: "https://d32dm0rphc51dk.cloudfront.net/UkZNg9J41gqfxCF3x5YSAg/large.jpg",
                  },
                  title: "Figure",
                  date: "1987",
                  sale_message: "Contact For Price",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Karel Appel", __id: "QXJ0aXN0OmthcmVsLWFwcGVs" }],
                  partner: { name: "Vallarino Fine Art", __id: "UGFydG5lcjp2YWxsYXJpbm8tZmluZS1hcnQ=" },
                  href: "/artwork/karel-appel-figure-1",
                },
              },
              {
                node: {
                  id: "ilya-bolotowsky-ellipse-with-yellows",
                  __id: "QXJ0d29yazppbHlhLWJvbG90b3dza3ktZWxsaXBzZS13aXRoLXllbGxvd3M=",
                  image: {
                    aspect_ratio: 0.71,
                    url: "https://d32dm0rphc51dk.cloudfront.net/0l0ElDvZ1InQkHzUOsDZUw/large.jpg",
                  },
                  title: "Ellipse with Yellows",
                  date: "1977",
                  sale_message: "Contact For Price",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Ilya Bolotowsky", __id: "QXJ0aXN0OmlseWEtYm9sb3Rvd3NreQ==" }],
                  partner: { name: "Vallarino Fine Art", __id: "UGFydG5lcjp2YWxsYXJpbm8tZmluZS1hcnQ=" },
                  href: "/artwork/ilya-bolotowsky-ellipse-with-yellows",
                },
              },
              {
                node: {
                  id: "ilya-bolotowsky-untitled-34",
                  __id: "QXJ0d29yazppbHlhLWJvbG90b3dza3ktdW50aXRsZWQtMzQ=",
                  image: {
                    aspect_ratio: 0.82,
                    url: "https://d32dm0rphc51dk.cloudfront.net/vazk_oud_vZlxYuwaBflsA/large.jpg",
                  },
                  title: "Untitled",
                  date: "1979",
                  sale_message: "Contact For Price",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Ilya Bolotowsky", __id: "QXJ0aXN0OmlseWEtYm9sb3Rvd3NreQ==" }],
                  partner: { name: "Vallarino Fine Art", __id: "UGFydG5lcjp2YWxsYXJpbm8tZmluZS1hcnQ=" },
                  href: "/artwork/ilya-bolotowsky-untitled-34",
                },
              },
              {
                node: {
                  id: "james-brooks-garee",
                  __id: "QXJ0d29yazpqYW1lcy1icm9va3MtZ2FyZWU=",
                  image: {
                    aspect_ratio: 1.15,
                    url: "https://d32dm0rphc51dk.cloudfront.net/3iKEv7QdqzHo4nv4Ha9qTw/large.jpg",
                  },
                  title: "Garee",
                  date: "1969",
                  sale_message: "Contact For Price",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "James Brooks", __id: "QXJ0aXN0OmphbWVzLWJyb29rcw==" }],
                  partner: { name: "Vallarino Fine Art", __id: "UGFydG5lcjp2YWxsYXJpbm8tZmluZS1hcnQ=" },
                  href: "/artwork/james-brooks-garee",
                },
              },
            ],
          },
          name: "Vallarino Fine Art at Art Palm Springs 2019",
          is_fair_booth: true,
          partner: {
            __typename: "Partner",
            name: "Vallarino Fine Art",
            href: "/vallarino-fine-art",
            id: "vallarino-fine-art",
            _id: "4e7b9b8392112b000100682b",
            __id: "UGFydG5lcjp2YWxsYXJpbm8tZmluZS1hcnQ=",
            profile: {
              _id: "5159da8d9a608324390000e1",
              is_followed: false,
              __id: "UHJvZmlsZTp2YWxsYXJpbm8tZmluZS1hcnQ=",
            },
          },
          fair: { name: "Art Palm Springs 2019", __id: "RmFpcjphcnQtcGFsbS1zcHJpbmdzLTIwMTk=" },
          cover_image: { url: "https://d32dm0rphc51dk.cloudfront.net/Bwu6LjbuAg0iWDKtfgH2Hw/medium.jpg" },
          location: { display: "Booth 303", __id: "TG9jYXRpb246NWMyZTUwNmIwY2YxMTAwMDA3YjQzOGEy" },
          __id: "U2hvdzp2YWxsYXJpbm8tZmluZS1hcnQtdmFsbGFyaW5vLWZpbmUtYXJ0LWF0LWFydC1wYWxtLXNwcmluZ3MtMjAxOQ==",
          __typename: "Show",
        },
      },
      {
        cursor: "YXJyYXljb25uZWN0aW9uOjQ=",
        node: {
          id: "simard-bilodeau-contemporary-simard-bilodeau-contemporary-at-art-palm-springs-2019",
          _id: "5c61a65ce6cbe34a2677f756",
          artworks_connection: {
            edges: [
              {
                node: {
                  id: "carrie-pearce-rococo",
                  __id: "QXJ0d29yazpjYXJyaWUtcGVhcmNlLXJvY29jbw==",
                  image: {
                    aspect_ratio: 0.66,
                    url: "https://d32dm0rphc51dk.cloudfront.net/h-zCD06TPPGPG3xRhmHpdQ/large.jpg",
                  },
                  title: "Rococo",
                  date: "2019",
                  sale_message: "$12,000",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Carrie Pearce", __id: "QXJ0aXN0OmNhcnJpZS1wZWFyY2U=" }],
                  partner: {
                    name: "Simard Bilodeau Contemporary",
                    __id: "UGFydG5lcjpzaW1hcmQtYmlsb2RlYXUtY29udGVtcG9yYXJ5",
                  },
                  href: "/artwork/carrie-pearce-rococo",
                },
              },
              {
                node: {
                  id: "yalda-sepahpour-golnar-i",
                  __id: "QXJ0d29yazp5YWxkYS1zZXBhaHBvdXItZ29sbmFyLWk=",
                  image: {
                    aspect_ratio: 1.54,
                    url: "https://d32dm0rphc51dk.cloudfront.net/sOIgbNlE3sXYkZnj2lkQeg/large.jpg",
                  },
                  title: "Golnar I",
                  date: "2019",
                  sale_message: "Sold",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Yalda Sepahpour", __id: "QXJ0aXN0OnlhbGRhLXNlcGFocG91cg==" }],
                  partner: {
                    name: "Simard Bilodeau Contemporary",
                    __id: "UGFydG5lcjpzaW1hcmQtYmlsb2RlYXUtY29udGVtcG9yYXJ5",
                  },
                  href: "/artwork/yalda-sepahpour-golnar-i",
                },
              },
              {
                node: {
                  id: "julie-bell-venus-clothed-in-flowers",
                  __id: "QXJ0d29yazpqdWxpZS1iZWxsLXZlbnVzLWNsb3RoZWQtaW4tZmxvd2Vycw==",
                  image: {
                    aspect_ratio: 0.5,
                    url: "https://d32dm0rphc51dk.cloudfront.net/2GC2s8xIV8dPRN3UsPYLkg/large.jpg",
                  },
                  title: "Venus Clothed in Flowers",
                  date: "",
                  sale_message: "$12,000",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Julie Bell", __id: "QXJ0aXN0Omp1bGllLWJlbGw=" }],
                  partner: {
                    name: "Simard Bilodeau Contemporary",
                    __id: "UGFydG5lcjpzaW1hcmQtYmlsb2RlYXUtY29udGVtcG9yYXJ5",
                  },
                  href: "/artwork/julie-bell-venus-clothed-in-flowers",
                },
              },
              {
                node: {
                  id: "val-ciel-etoile-2",
                  __id: "QXJ0d29yazp2YWwtY2llbC1ldG9pbGUtMg==",
                  image: {
                    aspect_ratio: 0.67,
                    url: "https://d32dm0rphc51dk.cloudfront.net/2C8qTfBZDmrk81_6z1hKlA/large.jpg",
                  },
                  title: "Ciel Étoilé",
                  date: "",
                  sale_message: "$14,800",
                  is_in_auction: false,
                  is_biddable: false,
                  is_acquireable: false,
                  is_offerable: false,
                  sale: null,
                  sale_artwork: null,
                  artists: [{ name: "Val", __id: "QXJ0aXN0OnZhbA==" }],
                  partner: {
                    name: "Simard Bilodeau Contemporary",
                    __id: "UGFydG5lcjpzaW1hcmQtYmlsb2RlYXUtY29udGVtcG9yYXJ5",
                  },
                  href: "/artwork/val-ciel-etoile-2",
                },
              },
            ],
          },
          name: "Simard Bilodeau Contemporary at Art Palm Springs 2019",
          is_fair_booth: true,
          partner: {
            __typename: "Partner",
            name: "Simard Bilodeau Contemporary",
            href: "/simard-bilodeau-contemporary",
            id: "simard-bilodeau-contemporary",
            _id: "54cacdda7261695f96470200",
            __id: "UGFydG5lcjpzaW1hcmQtYmlsb2RlYXUtY29udGVtcG9yYXJ5",
            profile: {
              _id: "54cacdda7261695f96490200",
              is_followed: false,
              __id: "UHJvZmlsZTpzaW1hcmQtYmlsb2RlYXUtY29udGVtcG9yYXJ5",
            },
          },
          fair: { name: "Art Palm Springs 2019", __id: "RmFpcjphcnQtcGFsbS1zcHJpbmdzLTIwMTk=" },
          cover_image: { url: "https://d32dm0rphc51dk.cloudfront.net/h-zCD06TPPGPG3xRhmHpdQ/larger.jpg" },
          location: { display: "Booth 310", __id: "TG9jYXRpb246NWM2MWE2NWNlNmNiZTM0YTI2NzdmNzU3" },
          __id:
            "U2hvdzpzaW1hcmQtYmlsb2RlYXUtY29udGVtcG9yYXJ5LXNpbWFyZC1iaWxvZGVhdS1jb250ZW1wb3JhcnktYXQtYXJ0LXBhbG0tc3ByaW5ncy0yMDE5",
          __typename: "Show",
        },
      },
    ],
  },
}
